name: Basic MLOps CI Workflow

on:
  push:
    branches:
      - main
      - vatsalya-changes
    paths:
      - 'data/**'
      - 'train/**'
      - 'requirements.txt'
  pull_request:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to checkout and run the workflow on'
        required: true
        default: 'main'
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
          - info
          - debug
          - warning

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Training Script
        run: python train/train.py

      - name: Upload Trained Model as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: ./model/

